"""
Extract coverage percentage from coverage.xml and generate a coverage badge JSON file.

This script parses the `coverage.xml` file generated by a code coverage tool (e.g., pytest-cov),
calculates the line coverage percentage, determines an appropriate color based on thresholds,
and outputs a JSON file to `badges/coverage.json` for a coverage badge.
"""

import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


def get_coverage_color(pct):
    """
    Determine the color for a coverage badge based on the coverage percentage.

    Parameters
    ----------
    pct : float
        The coverage percentage (0-100).

    Returns
    -------
    str
        The color name for the badge ('brightgreen', 'green', 'yellow', 'orange', or 'red').
    """
    if pct >= 90:
        return "brightgreen"
    if pct >= 80:
        return "green"
    if pct >= 70:
        return "yellow"
    if pct >= 60:
        return "orange"
    return "red"


# Check if coverage.xml exists
project_root = Path(__file__).parent.parent.parent
coverage_file = project_root / "coverage.xml"
print(f"Looking for coverage file at: {coverage_file}")
if not coverage_file.exists():
    print("Error: coverage.xml not found", file=sys.stderr)
    raise FileNotFoundError("coverage.xml not found")

# Parse coverage.xml
tree = ET.parse(coverage_file)
root = tree.getroot()
coverage = float(root.attrib["line-rate"]) * 100

# Create badges directory
badges_dir = project_root / "badges"
badges_dir.mkdir(exist_ok=True)

# Generate badge JSON
badge_data = {
    "schemaVersion": 1,
    "label": "coverage",
    "message": f"{coverage:.1f}%",
    "color": get_coverage_color(coverage),
}

with open(badges_dir / "coverage.json", "w", encoding="utf-8") as f:
    json.dump(badge_data, f, indent=2)

print(f"Coverage: {coverage:.1f}%")
