name: 'Setup Python Environment'
description: 'Checkout code, setup uv, configure cache, and setup nox'

inputs:
  python-version:
    description: 'Python version to use'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        prune-cache: false

    - uses: wntrblm/nox@2025.10.16
      with:
        python-versions: ${{ inputs.python-version }}
